export const SYSTEM_MODULES = [
  { name: 'Dashboard', description: 'System Dashboard and Analytics' },
  { name: 'Users', description: 'User Management' },
  { name: 'Roles & Permissions', description: 'Access Control Management' },
  { name: 'Business Units', description: 'Business Unit Configuration' },
  { name: 'Teams', description: 'Team and Department Management' },
  { name: 'User Groups', description: 'User Grouping' },
  { name: 'Currency', description: 'Currency Setup' },
  { name: 'Warehouse', description: 'Warehouse and Inventory Locations' },
  { name: 'UOM', description: 'Units of Measure' },
  { name: 'Locations', description: 'Country, State, and City Setup' },
  { name: 'Quote Configuration', description: 'RFQ and Quotation Settings' },
  { name: 'Products', description: 'Product Catalog Management' },
  { name: 'Product Categories', description: 'Product Categorization' },
  { name: 'RFQ Management', description: 'Request for Quotation Workflow' },
  { name: 'Quotations', description: 'Supplier Quotes and Analysis' },
  { name: 'Orders', description: 'Purchase and Sales Orders' },
  { name: 'Shipments', description: 'Logistics and Shipment Tracking' },
  { name: 'Customers', description: 'Customer Relationship Management' },
  { name: 'Suppliers', description: 'Supplier Management' },
  { name: 'Leads', description: 'Sales Lead Management' },
  { name: 'Email & SMTP', description: 'Communication and Server Settings' },
  { name: 'File Management', description: 'System Files and Uploads' },
  { name: 'Bulk Uploaders', description: 'Data Import Utilities' },
  { name: 'Supplier History', description: 'Supplier Purchase and Quote History' },
  { name: 'Contacts', description: 'Global Contact Directory' },
];
