namespace ERP_RFQ_Automation.Platform.Services;

/// <summary>
/// Immutable v1 country catalogue used by tenant provisioning and the matching upgrade migration.
/// Codes are the 249 ISO 3166-1 alpha-2 assignments; English display names are the customary UI
/// names published by Unicode CLDR 48. Existing tenant rows always win over these opening labels.
///
/// Keep this version frozen so an old migration remains deterministic. A future ISO change needs a
/// new catalogue version and a new migration rather than editing this list in place.
/// Sources:
/// https://www.iso.org/obp/ui/#search/code/
/// https://github.com/unicode-org/cldr-json/blob/main/cldr-json/cldr-localenames-full/main/en/territories.json
/// </summary>
public static class IsoCountryCatalogV1
{
    public sealed record CountryDefinition(string Code, string Name);

    public static readonly IReadOnlyList<CountryDefinition> Countries =
    [
        new("AD", "Andorra"),
        new("AE", "United Arab Emirates"),
        new("AF", "Afghanistan"),
        new("AG", "Antigua & Barbuda"),
        new("AI", "Anguilla"),
        new("AL", "Albania"),
        new("AM", "Armenia"),
        new("AO", "Angola"),
        new("AQ", "Antarctica"),
        new("AR", "Argentina"),
        new("AS", "American Samoa"),
        new("AT", "Austria"),
        new("AU", "Australia"),
        new("AW", "Aruba"),
        new("AX", "Åland Islands"),
        new("AZ", "Azerbaijan"),
        new("BA", "Bosnia & Herzegovina"),
        new("BB", "Barbados"),
        new("BD", "Bangladesh"),
        new("BE", "Belgium"),
        new("BF", "Burkina Faso"),
        new("BG", "Bulgaria"),
        new("BH", "Bahrain"),
        new("BI", "Burundi"),
        new("BJ", "Benin"),
        new("BL", "St. Barthélemy"),
        new("BM", "Bermuda"),
        new("BN", "Brunei"),
        new("BO", "Bolivia"),
        new("BQ", "Caribbean Netherlands"),
        new("BR", "Brazil"),
        new("BS", "Bahamas"),
        new("BT", "Bhutan"),
        new("BV", "Bouvet Island"),
        new("BW", "Botswana"),
        new("BY", "Belarus"),
        new("BZ", "Belize"),
        new("CA", "Canada"),
        new("CC", "Cocos (Keeling) Islands"),
        new("CD", "Congo - Kinshasa"),
        new("CF", "Central African Republic"),
        new("CG", "Congo - Brazzaville"),
        new("CH", "Switzerland"),
        new("CI", "Côte d’Ivoire"),
        new("CK", "Cook Islands"),
        new("CL", "Chile"),
        new("CM", "Cameroon"),
        new("CN", "China"),
        new("CO", "Colombia"),
        new("CR", "Costa Rica"),
        new("CU", "Cuba"),
        new("CV", "Cape Verde"),
        new("CW", "Curaçao"),
        new("CX", "Christmas Island"),
        new("CY", "Cyprus"),
        new("CZ", "Czechia"),
        new("DE", "Germany"),
        new("DJ", "Djibouti"),
        new("DK", "Denmark"),
        new("DM", "Dominica"),
        new("DO", "Dominican Republic"),
        new("DZ", "Algeria"),
        new("EC", "Ecuador"),
        new("EE", "Estonia"),
        new("EG", "Egypt"),
        new("EH", "Western Sahara"),
        new("ER", "Eritrea"),
        new("ES", "Spain"),
        new("ET", "Ethiopia"),
        new("FI", "Finland"),
        new("FJ", "Fiji"),
        new("FK", "Falkland Islands"),
        new("FM", "Micronesia"),
        new("FO", "Faroe Islands"),
        new("FR", "France"),
        new("GA", "Gabon"),
        new("GB", "United Kingdom"),
        new("GD", "Grenada"),
        new("GE", "Georgia"),
        new("GF", "French Guiana"),
        new("GG", "Guernsey"),
        new("GH", "Ghana"),
        new("GI", "Gibraltar"),
        new("GL", "Greenland"),
        new("GM", "Gambia"),
        new("GN", "Guinea"),
        new("GP", "Guadeloupe"),
        new("GQ", "Equatorial Guinea"),
        new("GR", "Greece"),
        new("GS", "South Georgia & South Sandwich Islands"),
        new("GT", "Guatemala"),
        new("GU", "Guam"),
        new("GW", "Guinea-Bissau"),
        new("GY", "Guyana"),
        new("HK", "Hong Kong SAR China"),
        new("HM", "Heard & McDonald Islands"),
        new("HN", "Honduras"),
        new("HR", "Croatia"),
        new("HT", "Haiti"),
        new("HU", "Hungary"),
        new("ID", "Indonesia"),
        new("IE", "Ireland"),
        new("IL", "Israel"),
        new("IM", "Isle of Man"),
        new("IN", "India"),
        new("IO", "British Indian Ocean Territory"),
        new("IQ", "Iraq"),
        new("IR", "Iran"),
        new("IS", "Iceland"),
        new("IT", "Italy"),
        new("JE", "Jersey"),
        new("JM", "Jamaica"),
        new("JO", "Jordan"),
        new("JP", "Japan"),
        new("KE", "Kenya"),
        new("KG", "Kyrgyzstan"),
        new("KH", "Cambodia"),
        new("KI", "Kiribati"),
        new("KM", "Comoros"),
        new("KN", "St. Kitts & Nevis"),
        new("KP", "North Korea"),
        new("KR", "South Korea"),
        new("KW", "Kuwait"),
        new("KY", "Cayman Islands"),
        new("KZ", "Kazakhstan"),
        new("LA", "Laos"),
        new("LB", "Lebanon"),
        new("LC", "St. Lucia"),
        new("LI", "Liechtenstein"),
        new("LK", "Sri Lanka"),
        new("LR", "Liberia"),
        new("LS", "Lesotho"),
        new("LT", "Lithuania"),
        new("LU", "Luxembourg"),
        new("LV", "Latvia"),
        new("LY", "Libya"),
        new("MA", "Morocco"),
        new("MC", "Monaco"),
        new("MD", "Moldova"),
        new("ME", "Montenegro"),
        new("MF", "St. Martin"),
        new("MG", "Madagascar"),
        new("MH", "Marshall Islands"),
        new("MK", "North Macedonia"),
        new("ML", "Mali"),
        new("MM", "Myanmar (Burma)"),
        new("MN", "Mongolia"),
        new("MO", "Macao SAR China"),
        new("MP", "Northern Mariana Islands"),
        new("MQ", "Martinique"),
        new("MR", "Mauritania"),
        new("MS", "Montserrat"),
        new("MT", "Malta"),
        new("MU", "Mauritius"),
        new("MV", "Maldives"),
        new("MW", "Malawi"),
        new("MX", "Mexico"),
        new("MY", "Malaysia"),
        new("MZ", "Mozambique"),
        new("NA", "Namibia"),
        new("NC", "New Caledonia"),
        new("NE", "Niger"),
        new("NF", "Norfolk Island"),
        new("NG", "Nigeria"),
        new("NI", "Nicaragua"),
        new("NL", "Netherlands"),
        new("NO", "Norway"),
        new("NP", "Nepal"),
        new("NR", "Nauru"),
        new("NU", "Niue"),
        new("NZ", "New Zealand"),
        new("OM", "Oman"),
        new("PA", "Panama"),
        new("PE", "Peru"),
        new("PF", "French Polynesia"),
        new("PG", "Papua New Guinea"),
        new("PH", "Philippines"),
        new("PK", "Pakistan"),
        new("PL", "Poland"),
        new("PM", "St. Pierre & Miquelon"),
        new("PN", "Pitcairn Islands"),
        new("PR", "Puerto Rico"),
        new("PS", "Palestinian Territories"),
        new("PT", "Portugal"),
        new("PW", "Palau"),
        new("PY", "Paraguay"),
        new("QA", "Qatar"),
        new("RE", "Réunion"),
        new("RO", "Romania"),
        new("RS", "Serbia"),
        new("RU", "Russia"),
        new("RW", "Rwanda"),
        new("SA", "Saudi Arabia"),
        new("SB", "Solomon Islands"),
        new("SC", "Seychelles"),
        new("SD", "Sudan"),
        new("SE", "Sweden"),
        new("SG", "Singapore"),
        new("SH", "St. Helena"),
        new("SI", "Slovenia"),
        new("SJ", "Svalbard & Jan Mayen"),
        new("SK", "Slovakia"),
        new("SL", "Sierra Leone"),
        new("SM", "San Marino"),
        new("SN", "Senegal"),
        new("SO", "Somalia"),
        new("SR", "Suriname"),
        new("SS", "South Sudan"),
        new("ST", "São Tomé & Príncipe"),
        new("SV", "El Salvador"),
        new("SX", "Sint Maarten"),
        new("SY", "Syria"),
        new("SZ", "Eswatini"),
        new("TC", "Turks & Caicos Islands"),
        new("TD", "Chad"),
        new("TF", "French Southern Territories"),
        new("TG", "Togo"),
        new("TH", "Thailand"),
        new("TJ", "Tajikistan"),
        new("TK", "Tokelau"),
        new("TL", "Timor-Leste"),
        new("TM", "Turkmenistan"),
        new("TN", "Tunisia"),
        new("TO", "Tonga"),
        new("TR", "Türkiye"),
        new("TT", "Trinidad & Tobago"),
        new("TV", "Tuvalu"),
        new("TW", "Taiwan"),
        new("TZ", "Tanzania"),
        new("UA", "Ukraine"),
        new("UG", "Uganda"),
        new("UM", "U.S. Outlying Islands"),
        new("US", "United States"),
        new("UY", "Uruguay"),
        new("UZ", "Uzbekistan"),
        new("VA", "Vatican City"),
        new("VC", "St. Vincent & Grenadines"),
        new("VE", "Venezuela"),
        new("VG", "British Virgin Islands"),
        new("VI", "U.S. Virgin Islands"),
        new("VN", "Vietnam"),
        new("VU", "Vanuatu"),
        new("WF", "Wallis & Futuna"),
        new("WS", "Samoa"),
        new("YE", "Yemen"),
        new("YT", "Mayotte"),
        new("ZA", "South Africa"),
        new("ZM", "Zambia"),
        new("ZW", "Zimbabwe"),
    ];
}
