using System.Text.RegularExpressions;
using ERP_RFQ_Automation.ListViews;

namespace ERP_RFQ_Automation.Tests.ListViews;

/// <summary>
/// AA-01 · the Customers grid and its column picker must describe the same grid.
///
/// The picker's count and its checkboxes come from <see cref="ListViewCatalog"/>; the columns
/// come from <c>Frontend/src/pages/Customers/CustomersPage.tsx</c>. When the page grew Account
/// team, Sector, Region, CR number and VAT number and the catalog did not, the client kept the
/// unknown columns (losing a column is worse) but appended them AFTER the locked Actions column
/// and left them out of the picker — so the picker said "7/10" over a grid showing thirteen, with
/// three columns dangling past the row buttons. These tests read the page source, the way the
/// release-acceptance tests do, so the two halves cannot drift again without a red build.
/// </summary>
public sealed class CustomersGridWiringTests
{
    private const string View = "customers.list";

    /// <summary>
    /// The `field: '…'` keys of the grid definitions in CustomersPage.tsx. Custom-field columns
    /// (`cf:` prefix) are generated by the client from the tenant's definitions and are not
    /// declared here.
    /// </summary>
    private static IReadOnlyList<string> RenderedFields()
    {
        var page = File.ReadAllText(Path.Combine(FindRepositoryRoot(), "Frontend/src/pages/Customers/CustomersPage.tsx"));
        return Regex.Matches(page, @"field:\s*'([A-Za-z][A-Za-z0-9]*)'")
            .Select(match => match.Groups[1].Value)
            .Distinct()
            .ToList();
    }

    [Fact]
    public void Every_column_the_Customers_page_renders_is_declared_in_the_catalog()
    {
        var view = ListViewCatalog.Find(View);
        Assert.NotNull(view);
        var declared = view!.Columns.Select(x => x.Key).ToHashSet(StringComparer.Ordinal);

        var rendered = RenderedFields();
        Assert.NotEmpty(rendered);
        var missing = rendered.Where(field => !declared.Contains(field)).ToList();
        Assert.True(missing.Count == 0,
            $"CustomersPage.tsx renders columns the customers.list catalog does not declare, so the " +
            $"picker cannot offer them and the count it shows is wrong: {string.Join(", ", missing)}");
    }

    [Fact]
    public void The_relationship_columns_are_on_by_default_and_the_registrations_are_off()
    {
        var view = ListViewCatalog.Find(View)!;
        foreach (var key in new[] { "accountTeamName", "sector", "regionName" })
            Assert.True(Assert.Single(view.Columns, x => x.Key == key).DefaultVisible, $"{key} should be on by default");
        foreach (var key in new[] { "commercialRegistrationNumber", "taxRegistrationNumber" })
            Assert.False(Assert.Single(view.Columns, x => x.Key == key).DefaultVisible, $"{key} should be off by default");
    }

    [Fact]
    public void Actions_is_the_last_column_and_cannot_be_hidden()
    {
        var view = ListViewCatalog.Find(View)!;
        var last = view.Columns[^1];
        Assert.Equal("actions", last.Key);
        Assert.True(last.Locked);
    }

    private static string FindRepositoryRoot()
    {
        var directory = new DirectoryInfo(AppContext.BaseDirectory);
        while (directory != null && !Directory.Exists(Path.Combine(directory.FullName, "Frontend")))
            directory = directory.Parent;
        return Assert.IsType<DirectoryInfo>(directory).FullName;
    }
}
