using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ERP_RFQ_Automation.Migrations;

/// <summary>
/// Focused commercial-decision migration. Existing standalone RFQs remain valid and therefore
/// retain null lineage; every new Lead-origin RFQ is written through RfqPromotionService.
/// </summary>
[DbContext(typeof(ERP_RFQ_Automation.Models.ErpRfqAutomationContext))]
[Migration("20260825043000_LeadParticipationAndRfqPromotion")]
public partial class LeadParticipationAndRfqPromotion : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("""
            -- Existing identity/RFQ tables use FORCE RLS, so even their owner cannot run the
            -- cross-tenant backfill or validate consistency keys without a tenant GUC. Lift
            -- FORCE only inside this transactional migration; ACCESS EXCLUSIVE locks prevent
            -- concurrent access and rollback restores the flags if any later statement fails.
            ALTER TABLE public."LeadItemRevisions" NO FORCE ROW LEVEL SECURITY;
            ALTER TABLE public."LeadRevisions" NO FORCE ROW LEVEL SECURITY;
            ALTER TABLE public."RFQ" NO FORCE ROW LEVEL SECURITY;

            ALTER TABLE "RFQ" ADD COLUMN IF NOT EXISTS "PromotionId" bigint NULL;
            ALTER TABLE "RFQ" ADD COLUMN IF NOT EXISTS "SourceLeadRevisionId" bigint NULL;
            ALTER TABLE "RFQ" ADD COLUMN IF NOT EXISTS "ParticipationDecisionId" bigint NULL;
            ALTER TABLE "RFQItems" ADD COLUMN IF NOT EXISTS "SourceBusinessUnitId" bigint NULL;
            ALTER TABLE "RFQItems" ADD COLUMN IF NOT EXISTS "SourceLeadId" bigint NULL;
            ALTER TABLE "RFQItems" ADD COLUMN IF NOT EXISTS "SourceLeadRevisionId" bigint NULL;
            ALTER TABLE "RFQItems" ADD COLUMN IF NOT EXISTS "SourceLeadItemRevisionId" bigint NULL;
            ALTER TABLE "LeadItemRevisions" ADD COLUMN IF NOT EXISTS "LeadId" bigint NULL;
            ALTER TABLE "LeadItemRevisions" ADD COLUMN IF NOT EXISTS "LeadItemId" bigint NULL;
            ALTER TABLE "LeadItems" ADD COLUMN IF NOT EXISTS "IsCurrentRevisionProjection" boolean NOT NULL DEFAULT TRUE;
            ALTER TABLE "LeadItems" ADD COLUMN IF NOT EXISTS "EvidenceSourceLeadItemId" bigint NULL;

            UPDATE "LeadItemRevisions" line
            SET "LeadId" = revision."LeadId"
            FROM "LeadRevisions" revision
            WHERE revision."BusinessUnitId" = line."BusinessUnitId"
              AND revision."Id" = line."LeadRevisionId"
              AND line."LeadId" IS NULL;

            WITH exact_candidates AS (
                SELECT line."Id" AS line_id, item."ID" AS item_id,
                       count(*) OVER (PARTITION BY line."Id") AS candidate_count
                FROM "LeadItemRevisions" line
                JOIN "LeadItems" item ON item."LeadID" = line."LeadId"
                WHERE regexp_replace(lower(coalesce(item."LineItemNo", '')), '[^[:alnum:]]', '', 'g')
                        = coalesce(line."SnapshotJson"->>'line', '')
                  AND regexp_replace(lower(coalesce(item."ManufacturerPartNumber", item."ItemMaterialCode", '')), '[^[:alnum:]]', '', 'g')
                        = coalesce(line."SnapshotJson"->>'part', '')
                  AND regexp_replace(lower(coalesce(item."ProductShortDescription", item."ItemText", '')), '[^[:alnum:]]', '', 'g')
                        = coalesce(line."SnapshotJson"->>'description', '')
                  AND regexp_replace(lower(btrim(coalesce(item."UnitOfMeasure", ''))), '[^[:alnum:]]', '', 'g')
                        = regexp_replace(lower(btrim(coalesce(line."SnapshotJson"->>'uom', ''))), '[^[:alnum:]]', '', 'g')
                  AND item."Quantity" IS NOT DISTINCT FROM NULLIF(line."SnapshotJson"->>'Quantity', '')::integer
            )
            UPDATE "LeadItemRevisions" line
            SET "LeadItemId" = candidate.item_id
            FROM exact_candidates candidate
            WHERE candidate.line_id = line."Id" AND candidate.candidate_count = 1
              AND line."LeadItemId" IS NULL;

            ALTER TABLE "LeadItemRevisions" ALTER COLUMN "LeadId" SET NOT NULL;

            CREATE TABLE "LeadFitAssessments" (
                "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "BusinessUnitId" bigint NOT NULL,
                "LeadId" bigint NOT NULL,
                "LeadRevisionId" bigint NOT NULL,
                "Sequence" integer NOT NULL,
                "PolicyVersion" varchar(64) NOT NULL,
                "Recommendation" varchar(32) NOT NULL,
                "IsActionable" boolean NOT NULL,
                "AssessmentJson" jsonb NOT NULL,
                "IdempotencyKey" varchar(256) NOT NULL,
                "RequestHash" character(64) NOT NULL,
                "AssessedBy" varchar(256) NOT NULL,
                "AssessedAtUtc" timestamptz NOT NULL,
                CONSTRAINT "AK_LeadFitAssessments_BusinessUnitId_Id" UNIQUE ("BusinessUnitId", "Id"),
                CONSTRAINT "FK_LeadFitAssessments_Leads" FOREIGN KEY ("BusinessUnitId", "LeadId")
                    REFERENCES "Leads" ("BusinessUnitID", "ID") ON DELETE RESTRICT,
                CONSTRAINT "FK_LeadFitAssessments_LeadRevisions" FOREIGN KEY ("BusinessUnitId", "LeadRevisionId")
                    REFERENCES "LeadRevisions" ("BusinessUnitId", "Id") ON DELETE RESTRICT
            );

            CREATE TABLE "LeadParticipationDecisions" (
                "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "BusinessUnitId" bigint NOT NULL,
                "LeadId" bigint NOT NULL,
                "LeadRevisionId" bigint NOT NULL,
                "FitAssessmentId" bigint NOT NULL,
                "Sequence" integer NOT NULL,
                "IsCommitted" boolean NOT NULL,
                "Outcome" varchar(24) NOT NULL,
                "ReasonCode" varchar(64) NULL,
                "Notes" varchar(2000) NULL,
                "IdempotencyKey" varchar(256) NOT NULL,
                "RequestHash" character(64) NOT NULL,
                "DecidedBy" varchar(256) NOT NULL,
                "DecidedAtUtc" timestamptz NOT NULL,
                CONSTRAINT "AK_LeadParticipationDecisions_BusinessUnitId_Id" UNIQUE ("BusinessUnitId", "Id"),
                CONSTRAINT "CK_LeadParticipationDecisions_Outcome" CHECK ("Outcome" IN ('Pending','FullBid','PartialBid','NoBid')),
                CONSTRAINT "FK_LeadParticipationDecisions_Leads" FOREIGN KEY ("BusinessUnitId", "LeadId")
                    REFERENCES "Leads" ("BusinessUnitID", "ID") ON DELETE RESTRICT,
                CONSTRAINT "FK_LeadParticipationDecisions_LeadRevisions" FOREIGN KEY ("BusinessUnitId", "LeadRevisionId")
                    REFERENCES "LeadRevisions" ("BusinessUnitId", "Id") ON DELETE RESTRICT,
                CONSTRAINT "FK_LeadParticipationDecisions_Fit" FOREIGN KEY ("BusinessUnitId", "FitAssessmentId")
                    REFERENCES "LeadFitAssessments" ("BusinessUnitId", "Id") ON DELETE RESTRICT
            );

            CREATE TABLE "LeadLineParticipationDecisions" (
                "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "BusinessUnitId" bigint NOT NULL,
                "LeadId" bigint NOT NULL,
                "LeadRevisionId" bigint NOT NULL,
                "ParticipationDecisionId" bigint NOT NULL,
                "LeadItemRevisionId" bigint NOT NULL,
                "Choice" varchar(16) NOT NULL,
                "ReasonCode" varchar(64) NULL,
                "ReasonNotes" varchar(2000) NULL,
                "ProductId" bigint NULL,
                "Quantity" integer NULL,
                "UnitOfMeasure" varchar(200) NULL,
                "UomId" integer NULL,
                "Currency" varchar(8) NULL,
                "CurrencyId" bigint NULL,
                "CatalogPolicyVersion" varchar(64) NOT NULL,
                "WarningSnapshotJson" jsonb NOT NULL,
                CONSTRAINT "CK_LeadLineParticipationDecisions_Choice" CHECK ("Choice" IN ('Pending','Bid','NoBid','Clarify')),
                CONSTRAINT "CK_LeadLineParticipationDecisions_NoBidReason" CHECK (
                    "Choice" NOT IN ('NoBid','Clarify') OR
                    (("ReasonCode" IS NOT NULL AND btrim("ReasonCode") <> '') OR
                     ("ReasonNotes" IS NOT NULL AND length(btrim("ReasonNotes")) >= 5))),
                CONSTRAINT "CK_LeadLineParticipationDecisions_Quantity" CHECK ("Quantity" IS NULL OR "Quantity" > 0),
                CONSTRAINT "CK_LeadLineParticipationDecisions_BidCommercialIdentity" CHECK (
                    "Choice" <> 'Bid' OR
                    ("Quantity" > 0 AND "UomId" IS NOT NULL AND "CurrencyId" IS NOT NULL AND
                     "UnitOfMeasure" IS NOT NULL AND btrim("UnitOfMeasure") <> '' AND
                     "Currency" IS NOT NULL AND btrim("Currency") <> '')),
                CONSTRAINT "FK_LeadLineParticipationDecisions_Uom" FOREIGN KEY ("BusinessUnitId", "UomId")
                    REFERENCES "setUOM" ("BusinessUnitID", "UomID") ON DELETE RESTRICT,
                CONSTRAINT "FK_LeadLineParticipationDecisions_Currency" FOREIGN KEY ("BusinessUnitId", "CurrencyId")
                    REFERENCES "Currency" ("BusinessUnitID", "ID") ON DELETE RESTRICT
            );

            CREATE TABLE "RfqPromotions" (
                "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "BusinessUnitId" bigint NOT NULL,
                "LeadId" bigint NOT NULL,
                "LeadRevisionId" bigint NOT NULL,
                "ParticipationDecisionId" bigint NOT NULL,
                "IdempotencyKey" varchar(256) NOT NULL,
                "RequestHash" character(64) NOT NULL,
                "PromotedBy" varchar(256) NOT NULL,
                "PromotedAtUtc" timestamptz NOT NULL,
                CONSTRAINT "AK_RfqPromotions_BusinessUnitId_Id" UNIQUE ("BusinessUnitId", "Id"),
                CONSTRAINT "FK_RfqPromotions_Leads" FOREIGN KEY ("BusinessUnitId", "LeadId")
                    REFERENCES "Leads" ("BusinessUnitID", "ID") ON DELETE RESTRICT,
                CONSTRAINT "FK_RfqPromotions_LeadRevisions" FOREIGN KEY ("BusinessUnitId", "LeadRevisionId")
                    REFERENCES "LeadRevisions" ("BusinessUnitId", "Id") ON DELETE RESTRICT,
                CONSTRAINT "FK_RfqPromotions_Decision" FOREIGN KEY ("BusinessUnitId", "ParticipationDecisionId")
                    REFERENCES "LeadParticipationDecisions" ("BusinessUnitId", "Id") ON DELETE RESTRICT
            );

            ALTER TABLE "LeadRevisions" ADD CONSTRAINT "AK_LeadRevisions_Tenant_Id_Lead"
                UNIQUE ("BusinessUnitId", "Id", "LeadId");
            ALTER TABLE "LeadItems" ADD CONSTRAINT "AK_LeadItems_Lead_Id"
                UNIQUE ("LeadID", "ID");
            ALTER TABLE "LeadFitAssessments" ADD CONSTRAINT "AK_LeadFitAssessments_Consistency"
                UNIQUE ("BusinessUnitId", "Id", "LeadId", "LeadRevisionId");
            ALTER TABLE "LeadParticipationDecisions" ADD CONSTRAINT "AK_LeadParticipationDecisions_Consistency"
                UNIQUE ("BusinessUnitId", "Id", "LeadId", "LeadRevisionId");
            ALTER TABLE "RfqPromotions" ADD CONSTRAINT "AK_RfqPromotions_Consistency"
                UNIQUE ("BusinessUnitId", "Id", "LeadId", "LeadRevisionId", "ParticipationDecisionId");
            ALTER TABLE "LeadItemRevisions" ADD CONSTRAINT "AK_LeadItemRevisions_SourceConsistency"
                UNIQUE ("BusinessUnitId", "Id", "LeadRevisionId", "LeadId");
            ALTER TABLE "RFQ" ADD CONSTRAINT "AK_RFQ_SourceConsistency"
                UNIQUE ("BusinessUnitID", "ID", "LeadID", "SourceLeadRevisionId");

            ALTER TABLE "LeadItemRevisions" ADD CONSTRAINT "FK_LeadItemRevisions_RevisionConsistency"
                FOREIGN KEY ("BusinessUnitId", "LeadRevisionId", "LeadId")
                REFERENCES "LeadRevisions" ("BusinessUnitId", "Id", "LeadId") ON DELETE RESTRICT;
            ALTER TABLE "LeadItemRevisions" ADD CONSTRAINT "FK_LeadItemRevisions_LeadItem"
                FOREIGN KEY ("LeadId", "LeadItemId") REFERENCES "LeadItems" ("LeadID", "ID") ON DELETE RESTRICT;
            ALTER TABLE "LeadFitAssessments" ADD CONSTRAINT "FK_LeadFitAssessments_RevisionConsistency"
                FOREIGN KEY ("BusinessUnitId", "LeadRevisionId", "LeadId")
                REFERENCES "LeadRevisions" ("BusinessUnitId", "Id", "LeadId") ON DELETE RESTRICT;
            ALTER TABLE "LeadParticipationDecisions" ADD CONSTRAINT "FK_LeadParticipationDecisions_RevisionConsistency"
                FOREIGN KEY ("BusinessUnitId", "LeadRevisionId", "LeadId")
                REFERENCES "LeadRevisions" ("BusinessUnitId", "Id", "LeadId") ON DELETE RESTRICT;
            ALTER TABLE "LeadParticipationDecisions" ADD CONSTRAINT "FK_LeadParticipationDecisions_FitConsistency"
                FOREIGN KEY ("BusinessUnitId", "FitAssessmentId", "LeadId", "LeadRevisionId")
                REFERENCES "LeadFitAssessments" ("BusinessUnitId", "Id", "LeadId", "LeadRevisionId") ON DELETE RESTRICT;
            ALTER TABLE "LeadLineParticipationDecisions" ADD CONSTRAINT "FK_LeadLineParticipationDecisions_DecisionConsistency"
                FOREIGN KEY ("BusinessUnitId", "ParticipationDecisionId", "LeadId", "LeadRevisionId")
                REFERENCES "LeadParticipationDecisions" ("BusinessUnitId", "Id", "LeadId", "LeadRevisionId") ON DELETE RESTRICT;
            ALTER TABLE "LeadLineParticipationDecisions" ADD CONSTRAINT "FK_LeadLineParticipationDecisions_RevisionLineConsistency"
                FOREIGN KEY ("BusinessUnitId", "LeadItemRevisionId", "LeadRevisionId", "LeadId")
                REFERENCES "LeadItemRevisions" ("BusinessUnitId", "Id", "LeadRevisionId", "LeadId") ON DELETE RESTRICT;
            ALTER TABLE "RfqPromotions" ADD CONSTRAINT "FK_RfqPromotions_RevisionConsistency"
                FOREIGN KEY ("BusinessUnitId", "LeadRevisionId", "LeadId")
                REFERENCES "LeadRevisions" ("BusinessUnitId", "Id", "LeadId") ON DELETE RESTRICT;
            ALTER TABLE "RfqPromotions" ADD CONSTRAINT "FK_RfqPromotions_DecisionConsistency"
                FOREIGN KEY ("BusinessUnitId", "ParticipationDecisionId", "LeadId", "LeadRevisionId")
                REFERENCES "LeadParticipationDecisions" ("BusinessUnitId", "Id", "LeadId", "LeadRevisionId") ON DELETE RESTRICT;

            CREATE UNIQUE INDEX "IX_LeadFitAssessments_BusinessUnitId_IdempotencyKey"
                ON "LeadFitAssessments" ("BusinessUnitId", "IdempotencyKey");
            CREATE UNIQUE INDEX "IX_LeadFitAssessments_BusinessUnitId_LeadRevisionId_Sequence"
                ON "LeadFitAssessments" ("BusinessUnitId", "LeadRevisionId", "Sequence");
            CREATE INDEX "IX_LeadFitAssessments_BusinessUnitId_LeadId"
                ON "LeadFitAssessments" ("BusinessUnitId", "LeadId");
            CREATE INDEX "IX_LeadFitAssessments_BusinessUnitId_LeadRevisionId_LeadId"
                ON "LeadFitAssessments" ("BusinessUnitId", "LeadRevisionId", "LeadId");
            CREATE UNIQUE INDEX "IX_LeadParticipationDecisions_BusinessUnitId_IdempotencyKey"
                ON "LeadParticipationDecisions" ("BusinessUnitId", "IdempotencyKey");
            CREATE UNIQUE INDEX "IX_LeadParticipationDecisions_BusinessUnitId_LeadRevisionId_Sequence"
                ON "LeadParticipationDecisions" ("BusinessUnitId", "LeadRevisionId", "Sequence");
            CREATE INDEX "IX_LeadParticipationDecisions_BusinessUnitId_LeadId"
                ON "LeadParticipationDecisions" ("BusinessUnitId", "LeadId");
            CREATE INDEX "IX_LeadParticipationDecisions_BusinessUnitId_LeadRevisionId_Le~"
                ON "LeadParticipationDecisions" ("BusinessUnitId", "LeadRevisionId", "LeadId");
            CREATE INDEX "IX_LeadParticipationDecisions_BusinessUnitId_FitAssessmentId_L~"
                ON "LeadParticipationDecisions" ("BusinessUnitId", "FitAssessmentId", "LeadId", "LeadRevisionId");
            CREATE UNIQUE INDEX "IX_LeadLineParticipationDecisions_BusinessUnitId_Participation~"
                ON "LeadLineParticipationDecisions" ("BusinessUnitId", "ParticipationDecisionId", "LeadItemRevisionId");
            CREATE INDEX "IX_LeadLineParticipationDecisions_BusinessUnitId_LeadItemRevis~"
                ON "LeadLineParticipationDecisions" ("BusinessUnitId", "LeadItemRevisionId", "LeadRevisionId", "LeadId");
            CREATE INDEX "IX_LeadLineParticipationDecisions_BusinessUnitId_Participatio~1"
                ON "LeadLineParticipationDecisions" ("BusinessUnitId", "ParticipationDecisionId", "LeadId", "LeadRevisionId");
            CREATE INDEX "IX_LeadLineParticipationDecisions_BusinessUnitId_UomId"
                ON "LeadLineParticipationDecisions" ("BusinessUnitId", "UomId");
            CREATE INDEX "IX_LeadLineParticipationDecisions_BusinessUnitId_CurrencyId"
                ON "LeadLineParticipationDecisions" ("BusinessUnitId", "CurrencyId");
            CREATE UNIQUE INDEX "IX_RfqPromotions_BusinessUnitId_IdempotencyKey"
                ON "RfqPromotions" ("BusinessUnitId", "IdempotencyKey");
            CREATE UNIQUE INDEX "IX_RfqPromotions_BusinessUnitId_ParticipationDecisionId"
                ON "RfqPromotions" ("BusinessUnitId", "ParticipationDecisionId");
            CREATE INDEX "IX_RfqPromotions_BusinessUnitId_LeadId"
                ON "RfqPromotions" ("BusinessUnitId", "LeadId");
            CREATE INDEX "IX_RfqPromotions_BusinessUnitId_LeadRevisionId_LeadId"
                ON "RfqPromotions" ("BusinessUnitId", "LeadRevisionId", "LeadId");
            CREATE INDEX "IX_RfqPromotions_BusinessUnitId_ParticipationDecisionId_LeadId~"
                ON "RfqPromotions" ("BusinessUnitId", "ParticipationDecisionId", "LeadId", "LeadRevisionId");
            CREATE INDEX "IX_LeadItemRevisions_BusinessUnitId_LeadRevisionId_LeadId"
                ON "LeadItemRevisions" ("BusinessUnitId", "LeadRevisionId", "LeadId");
            CREATE UNIQUE INDEX "IX_RFQ_BusinessUnitID_PromotionId" ON "RFQ" ("BusinessUnitID", "PromotionId")
                WHERE "PromotionId" IS NOT NULL;
            CREATE INDEX "IX_RFQ_BusinessUnitID_ParticipationDecisionId"
                ON "RFQ" ("BusinessUnitID", "ParticipationDecisionId");
            CREATE INDEX "IX_RFQ_BusinessUnitID_SourceLeadRevisionId"
                ON "RFQ" ("BusinessUnitID", "SourceLeadRevisionId");
            CREATE UNIQUE INDEX "IX_RFQ_BusinessUnitID_PromotionId_LeadID_SourceLeadRevisionId_~"
                ON "RFQ" ("BusinessUnitID", "PromotionId", "LeadID", "SourceLeadRevisionId", "ParticipationDecisionId");
            CREATE INDEX "IX_RFQItems_SourceBusinessUnitId_SourceLeadItemRevisionId"
                ON "RFQItems" ("SourceBusinessUnitId", "SourceLeadItemRevisionId");
            CREATE INDEX "IX_RFQItems_SourceBusinessUnitId_SourceLeadItemRevisionId_Sour~"
                ON "RFQItems" ("SourceBusinessUnitId", "SourceLeadItemRevisionId", "SourceLeadRevisionId", "SourceLeadId");
            CREATE INDEX "IX_LeadItems_LeadId_IsCurrentRevisionProjection"
                ON "LeadItems" ("LeadID", "IsCurrentRevisionProjection");
            CREATE INDEX "IX_LeadItems_LeadId_EvidenceSourceLeadItemId"
                ON "LeadItems" ("LeadID", "EvidenceSourceLeadItemId");
            ALTER TABLE "LeadItems" ADD CONSTRAINT "FK_LeadItems_EvidenceSource"
                FOREIGN KEY ("LeadID", "EvidenceSourceLeadItemId")
                REFERENCES "LeadItems" ("LeadID", "ID") ON DELETE RESTRICT;

            ALTER TABLE "RFQ" ADD CONSTRAINT "CK_RFQ_LeadPromotionLineage" CHECK (
                ("LeadID" IS NULL AND "PromotionId" IS NULL AND "SourceLeadRevisionId" IS NULL AND "ParticipationDecisionId" IS NULL) OR
                ("LeadID" IS NOT NULL AND "PromotionId" IS NOT NULL AND "SourceLeadRevisionId" IS NOT NULL AND "ParticipationDecisionId" IS NOT NULL)
            ) NOT VALID;
            ALTER TABLE "RFQItems" ADD CONSTRAINT "CK_RFQItems_SourceLineage" CHECK (
                ("SourceBusinessUnitId" IS NULL AND "SourceLeadId" IS NULL AND "SourceLeadRevisionId" IS NULL AND "SourceLeadItemRevisionId" IS NULL) OR
                ("SourceBusinessUnitId" IS NOT NULL AND "SourceLeadId" IS NOT NULL AND "SourceLeadRevisionId" IS NOT NULL AND "SourceLeadItemRevisionId" IS NOT NULL)
            ) NOT VALID;

            ALTER TABLE "RFQ" ADD CONSTRAINT "FK_RFQ_RfqPromotions"
                FOREIGN KEY ("BusinessUnitID", "PromotionId") REFERENCES "RfqPromotions" ("BusinessUnitId", "Id") ON DELETE RESTRICT;
            ALTER TABLE "RFQ" ADD CONSTRAINT "FK_RFQ_PromotionConsistency"
                FOREIGN KEY ("BusinessUnitID", "PromotionId", "LeadID", "SourceLeadRevisionId", "ParticipationDecisionId")
                REFERENCES "RfqPromotions" ("BusinessUnitId", "Id", "LeadId", "LeadRevisionId", "ParticipationDecisionId") ON DELETE RESTRICT;
            ALTER TABLE "RFQ" ADD CONSTRAINT "FK_RFQ_SourceLeadRevision"
                FOREIGN KEY ("BusinessUnitID", "SourceLeadRevisionId") REFERENCES "LeadRevisions" ("BusinessUnitId", "Id") ON DELETE RESTRICT;
            ALTER TABLE "RFQ" ADD CONSTRAINT "FK_RFQ_ParticipationDecision"
                FOREIGN KEY ("BusinessUnitID", "ParticipationDecisionId") REFERENCES "LeadParticipationDecisions" ("BusinessUnitId", "Id") ON DELETE RESTRICT;
            ALTER TABLE "RFQItems" ADD CONSTRAINT "FK_RFQItems_SourceLeadItemRevision"
                FOREIGN KEY ("SourceBusinessUnitId", "SourceLeadItemRevisionId", "SourceLeadRevisionId", "SourceLeadId")
                REFERENCES "LeadItemRevisions" ("BusinessUnitId", "Id", "LeadRevisionId", "LeadId") ON DELETE RESTRICT;
            ALTER TABLE "RFQItems" ADD CONSTRAINT "FK_RFQItems_ParentSourceConsistency"
                FOREIGN KEY ("SourceBusinessUnitId", "RFQID", "SourceLeadId", "SourceLeadRevisionId")
                REFERENCES "RFQ" ("BusinessUnitID", "ID", "LeadID", "SourceLeadRevisionId") ON DELETE RESTRICT;

            ALTER TABLE public."LeadItemRevisions" FORCE ROW LEVEL SECURITY;
            ALTER TABLE public."LeadRevisions" FORCE ROW LEVEL SECURITY;
            ALTER TABLE public."RFQ" FORCE ROW LEVEL SECURITY;

            DO $$
            DECLARE target text;
            BEGIN
                FOREACH target IN ARRAY ARRAY['LeadItemRevisions', 'LeadRevisions', 'RFQ'] LOOP
                    IF NOT (SELECT relforcerowsecurity FROM pg_class
                            WHERE oid = format('public.%I', target)::regclass) THEN
                        RAISE EXCEPTION '% lost FORCE ROW LEVEL SECURITY during migration 20260825043000.', target;
                    END IF;
                END LOOP;
            END $$;

            ALTER TABLE public."LeadFitAssessments" ENABLE ROW LEVEL SECURITY;
            ALTER TABLE public."LeadFitAssessments" FORCE ROW LEVEL SECURITY;
            CREATE POLICY nexora_tenant_isolation ON public."LeadFitAssessments" TO nexora_tenant_app
                USING ("BusinessUnitId" = NULLIF(current_setting('nexora.business_unit_id', true), '')::bigint)
                WITH CHECK ("BusinessUnitId" = NULLIF(current_setting('nexora.business_unit_id', true), '')::bigint);
            ALTER TABLE public."LeadParticipationDecisions" ENABLE ROW LEVEL SECURITY;
            ALTER TABLE public."LeadParticipationDecisions" FORCE ROW LEVEL SECURITY;
            CREATE POLICY nexora_tenant_isolation ON public."LeadParticipationDecisions" TO nexora_tenant_app
                USING ("BusinessUnitId" = NULLIF(current_setting('nexora.business_unit_id', true), '')::bigint)
                WITH CHECK ("BusinessUnitId" = NULLIF(current_setting('nexora.business_unit_id', true), '')::bigint);
            ALTER TABLE public."LeadLineParticipationDecisions" ENABLE ROW LEVEL SECURITY;
            ALTER TABLE public."LeadLineParticipationDecisions" FORCE ROW LEVEL SECURITY;
            CREATE POLICY nexora_tenant_isolation ON public."LeadLineParticipationDecisions" TO nexora_tenant_app
                USING ("BusinessUnitId" = NULLIF(current_setting('nexora.business_unit_id', true), '')::bigint)
                WITH CHECK ("BusinessUnitId" = NULLIF(current_setting('nexora.business_unit_id', true), '')::bigint);
            ALTER TABLE public."RfqPromotions" ENABLE ROW LEVEL SECURITY;
            ALTER TABLE public."RfqPromotions" FORCE ROW LEVEL SECURITY;
            CREATE POLICY nexora_tenant_isolation ON public."RfqPromotions" TO nexora_tenant_app
                USING ("BusinessUnitId" = NULLIF(current_setting('nexora.business_unit_id', true), '')::bigint)
                WITH CHECK ("BusinessUnitId" = NULLIF(current_setting('nexora.business_unit_id', true), '')::bigint);

            GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE
                public."LeadFitAssessments", public."LeadParticipationDecisions",
                public."LeadLineParticipationDecisions", public."RfqPromotions"
            TO nexora_tenant_app;
            GRANT USAGE ON SEQUENCE
                public."LeadFitAssessments_Id_seq", public."LeadParticipationDecisions_Id_seq",
                public."LeadLineParticipationDecisions_Id_seq", public."RfqPromotions_Id_seq"
            TO nexora_tenant_app;

            DO $rls$
            DECLARE target text;
            BEGIN
                IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'nexora_purge_app') THEN
                    FOREACH target IN ARRAY ARRAY['LeadFitAssessments','LeadParticipationDecisions','LeadLineParticipationDecisions','RfqPromotions']
                    LOOP
                        EXECUTE format('GRANT SELECT, DELETE ON public.%I TO nexora_purge_app', target);
                        EXECUTE format(
                            'CREATE POLICY nexora_tenant_purge ON public.%I AS PERMISSIVE FOR ALL TO nexora_purge_app USING ("BusinessUnitId" = NULLIF(current_setting(''nexora.purge_business_unit_id'', true), '''')::bigint)',
                            target);
                    END LOOP;
                END IF;
            END
            $rls$;

            CREATE OR REPLACE FUNCTION nexora_reject_append_only_commercial_mutation()
            RETURNS trigger LANGUAGE plpgsql AS $$
            BEGIN
                RAISE EXCEPTION '% is append-only; write a new revision/decision instead', TG_TABLE_NAME
                    USING ERRCODE = '55000';
            END $$;

            CREATE TRIGGER "TR_LeadFitAssessments_AppendOnly" BEFORE UPDATE OR DELETE ON "LeadFitAssessments"
                FOR EACH ROW EXECUTE FUNCTION nexora_reject_append_only_commercial_mutation();
            CREATE TRIGGER "TR_LeadParticipationDecisions_AppendOnly" BEFORE UPDATE OR DELETE ON "LeadParticipationDecisions"
                FOR EACH ROW EXECUTE FUNCTION nexora_reject_append_only_commercial_mutation();
            CREATE TRIGGER "TR_LeadLineParticipationDecisions_AppendOnly" BEFORE UPDATE OR DELETE ON "LeadLineParticipationDecisions"
                FOR EACH ROW EXECUTE FUNCTION nexora_reject_append_only_commercial_mutation();
            CREATE TRIGGER "TR_RfqPromotions_AppendOnly" BEFORE UPDATE OR DELETE ON "RfqPromotions"
                FOR EACH ROW EXECUTE FUNCTION nexora_reject_append_only_commercial_mutation();
            CREATE TRIGGER "TR_LeadRevisions_AppendOnly" BEFORE UPDATE OR DELETE ON "LeadRevisions"
                FOR EACH ROW EXECUTE FUNCTION nexora_reject_append_only_commercial_mutation();
            CREATE TRIGGER "TR_LeadItemRevisions_AppendOnly" BEFORE UPDATE OR DELETE ON "LeadItemRevisions"
                FOR EACH ROW EXECUTE FUNCTION nexora_reject_append_only_commercial_mutation();
            """);
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("""
            REVOKE USAGE ON SEQUENCE public."LeadFitAssessments_Id_seq", public."LeadParticipationDecisions_Id_seq",
                public."LeadLineParticipationDecisions_Id_seq", public."RfqPromotions_Id_seq" FROM nexora_tenant_app;
            REVOKE ALL PRIVILEGES ON TABLE public."LeadFitAssessments", public."LeadParticipationDecisions",
                public."LeadLineParticipationDecisions", public."RfqPromotions" FROM nexora_tenant_app;
            DROP POLICY IF EXISTS nexora_tenant_purge ON public."RfqPromotions";
            DROP POLICY IF EXISTS nexora_tenant_purge ON public."LeadLineParticipationDecisions";
            DROP POLICY IF EXISTS nexora_tenant_purge ON public."LeadParticipationDecisions";
            DROP POLICY IF EXISTS nexora_tenant_purge ON public."LeadFitAssessments";
            DROP POLICY IF EXISTS nexora_tenant_isolation ON public."RfqPromotions";
            DROP POLICY IF EXISTS nexora_tenant_isolation ON public."LeadLineParticipationDecisions";
            DROP POLICY IF EXISTS nexora_tenant_isolation ON public."LeadParticipationDecisions";
            DROP POLICY IF EXISTS nexora_tenant_isolation ON public."LeadFitAssessments";
            DROP TRIGGER IF EXISTS "TR_RfqPromotions_AppendOnly" ON "RfqPromotions";
            DROP TRIGGER IF EXISTS "TR_LeadItemRevisions_AppendOnly" ON "LeadItemRevisions";
            DROP TRIGGER IF EXISTS "TR_LeadRevisions_AppendOnly" ON "LeadRevisions";
            DROP TRIGGER IF EXISTS "TR_LeadLineParticipationDecisions_AppendOnly" ON "LeadLineParticipationDecisions";
            DROP TRIGGER IF EXISTS "TR_LeadParticipationDecisions_AppendOnly" ON "LeadParticipationDecisions";
            DROP TRIGGER IF EXISTS "TR_LeadFitAssessments_AppendOnly" ON "LeadFitAssessments";
            DROP FUNCTION IF EXISTS nexora_reject_append_only_commercial_mutation();
            ALTER TABLE "RFQItems" DROP CONSTRAINT IF EXISTS "FK_RFQItems_SourceLeadItemRevision";
            ALTER TABLE "RFQItems" DROP CONSTRAINT IF EXISTS "FK_RFQItems_ParentSourceConsistency";
            ALTER TABLE "RFQ" DROP CONSTRAINT IF EXISTS "FK_RFQ_PromotionConsistency";
            ALTER TABLE "RFQItems" DROP CONSTRAINT IF EXISTS "CK_RFQItems_SourceLineage";
            ALTER TABLE "RFQ" DROP CONSTRAINT IF EXISTS "CK_RFQ_LeadPromotionLineage";
            ALTER TABLE "RFQ" DROP CONSTRAINT IF EXISTS "FK_RFQ_ParticipationDecision";
            ALTER TABLE "RFQ" DROP CONSTRAINT IF EXISTS "FK_RFQ_SourceLeadRevision";
            ALTER TABLE "RFQ" DROP CONSTRAINT IF EXISTS "FK_RFQ_RfqPromotions";
            ALTER TABLE "RfqPromotions" DROP CONSTRAINT IF EXISTS "FK_RfqPromotions_DecisionConsistency";
            ALTER TABLE "RfqPromotions" DROP CONSTRAINT IF EXISTS "FK_RfqPromotions_RevisionConsistency";
            ALTER TABLE "LeadParticipationDecisions" DROP CONSTRAINT IF EXISTS "FK_LeadParticipationDecisions_FitConsistency";
            ALTER TABLE "LeadParticipationDecisions" DROP CONSTRAINT IF EXISTS "FK_LeadParticipationDecisions_RevisionConsistency";
            ALTER TABLE "LeadLineParticipationDecisions" DROP CONSTRAINT IF EXISTS "FK_LeadLineParticipationDecisions_RevisionLineConsistency";
            ALTER TABLE "LeadLineParticipationDecisions" DROP CONSTRAINT IF EXISTS "FK_LeadLineParticipationDecisions_DecisionConsistency";
            ALTER TABLE "LeadFitAssessments" DROP CONSTRAINT IF EXISTS "FK_LeadFitAssessments_RevisionConsistency";
            ALTER TABLE "LeadItemRevisions" DROP CONSTRAINT IF EXISTS "FK_LeadItemRevisions_LeadItem";
            ALTER TABLE "LeadItemRevisions" DROP CONSTRAINT IF EXISTS "FK_LeadItemRevisions_RevisionConsistency";
            DROP TABLE IF EXISTS "RfqPromotions";
            DROP TABLE IF EXISTS "LeadLineParticipationDecisions";
            DROP TABLE IF EXISTS "LeadParticipationDecisions";
            DROP TABLE IF EXISTS "LeadFitAssessments";
            ALTER TABLE "LeadItems" DROP CONSTRAINT IF EXISTS "FK_LeadItems_EvidenceSource";
            ALTER TABLE "LeadItems" DROP CONSTRAINT IF EXISTS "AK_LeadItems_Lead_Id";
            ALTER TABLE "LeadRevisions" DROP CONSTRAINT IF EXISTS "AK_LeadRevisions_Tenant_Id_Lead";
            ALTER TABLE "RFQ" DROP CONSTRAINT IF EXISTS "AK_RFQ_SourceConsistency";
            ALTER TABLE "LeadItemRevisions" DROP CONSTRAINT IF EXISTS "AK_LeadItemRevisions_SourceConsistency";
            ALTER TABLE "LeadItemRevisions" DROP COLUMN IF EXISTS "LeadItemId";
            ALTER TABLE "LeadItemRevisions" DROP COLUMN IF EXISTS "LeadId";
            ALTER TABLE "LeadItems" DROP COLUMN IF EXISTS "IsCurrentRevisionProjection";
            ALTER TABLE "LeadItems" DROP COLUMN IF EXISTS "EvidenceSourceLeadItemId";
            ALTER TABLE "RFQItems" DROP COLUMN IF EXISTS "SourceLeadItemRevisionId";
            ALTER TABLE "RFQItems" DROP COLUMN IF EXISTS "SourceLeadRevisionId";
            ALTER TABLE "RFQItems" DROP COLUMN IF EXISTS "SourceLeadId";
            ALTER TABLE "RFQItems" DROP COLUMN IF EXISTS "SourceBusinessUnitId";
            ALTER TABLE "RFQ" DROP COLUMN IF EXISTS "ParticipationDecisionId";
            ALTER TABLE "RFQ" DROP COLUMN IF EXISTS "SourceLeadRevisionId";
            ALTER TABLE "RFQ" DROP COLUMN IF EXISTS "PromotionId";
            """);
    }
}
