using System.Globalization;
using System.Text;
using System.Text.RegularExpressions;

namespace ERP_RFQ_Automation.Extraction.Templates;

/// <summary>
/// One parsed line of an Aramco bid materials list.
/// </summary>
/// <param name="BidLine">The sheet's own line number (10, 20, 30 …), kept verbatim.</param>
/// <param name="ItemNo">The 9-digit Aramco material number — the customer's own code.</param>
/// <param name="ShipTo">Destination plant code.</param>
/// <param name="ReqUnit">Unit of measure exactly as the sheet wrote it. Never translated here.</param>
/// <param name="ReqQty">Required quantity.</param>
/// <param name="Description">Short noun line plus its full specification block.</param>
public sealed record AramcoBidLine(
    string BidLine, string ItemNo, string ShipTo, string ReqUnit, decimal ReqQty, string Description);

/// <param name="Lines">Parsed lines, document order.</param>
/// <param name="Bidno">The customer's own bid number — becomes the Lead's RFQ reference.</param>
/// <param name="Rejection">Null when the parse is trustworthy; otherwise why it must not be used.</param>
public sealed record AramcoBidList(
    IReadOnlyList<AramcoBidLine> Lines, string? Bidno, string? VendorCode,
    string? Buyer, DateOnly? BidDate, DateOnly? BidClose, string? Rejection)
{
    public bool IsTrustworthy => Rejection is null && Lines.Count > 0;
}

/// <summary>
/// Reads a Saudi Aramco "MATERIALS E-BIDDING SYSTEM — Bid Materials List" deterministically,
/// at zero token cost.
///
/// <para><b>Why this exists.</b> These documents are machine-generated by the customer's own
/// bidding system, arrive in volume, and are rigidly regular. Sending them to a language model
/// costs roughly 5,500 tokens per 23 items and returns a worse answer than reading the columns:
/// one 54-page bid consumed an entire tenant's monthly token budget and came back with 24 of
/// 1,603 lines. Per-token cost also rises with document size, so the biggest and most valuable
/// bids were the most expensive to read — exactly backwards.</para>
///
/// <para><b>The shape.</b> A masthead, two label/value blocks, a six-column header, then one
/// record per line item — five values in fixed order followed by the specification block:</para>
/// <code>
/// Bid Line | Item No | Ship To | Req Unit | Req Qty | Resp Qty
/// 10
/// 902017274
/// 3801
/// EA
/// 176
/// KEY:SHAFT,SQUARE,10 MM X 10 MM LG,X22CRM   ← description, then spec lines
/// 20
/// 902017276 …
/// </code>
///
/// <para><b>It refuses rather than guesses.</b> This is the central risk of moving extraction
/// in-house: a model that cannot read a document says so, while a template that maps the
/// quantity column onto the price column produces a quote that looks perfectly correct. Every
/// deviation from the expected shape returns a <see cref="AramcoBidList.Rejection"/> and the
/// caller falls through to the model. A partial parse is never returned — an under-quoted bid
/// is worse than an expensive one.</para>
/// </summary>
public static partial class AramcoBidListParser
{
    /// <summary>The masthead. Present on every document from this system, and on nothing else.</summary>
    private const string Masthead = "MATERIALS E-BIDDING SYSTEM";

    /// <summary>The six column headers, in the order the sheet always writes them.</summary>
    private static readonly string[] ColumnHeaders =
        ["Bid Line", "Item No", "Ship To", "Req Unit", "Req Qty", "Resp Qty"];

    /// <summary>
    /// An Aramco material number is exactly nine digits. The width is load-bearing: a looser
    /// <c>\d{6,}</c> also matched the seven-digit vendor code in the masthead and bare numbers
    /// inside specification text, so the completeness cross-check counted phantom items and
    /// refused every document in the corpus.
    /// </summary>
    [GeneratedRegex(@"^\d{9}$", RegexOptions.CultureInvariant)]
    private static partial Regex MaterialNumber();

    [GeneratedRegex(@"^\d{1,6}$", RegexOptions.CultureInvariant)]
    private static partial Regex BidLineNumber();

    /// <summary>A unit as the sheet writes it: short, alphabetic, no digits.</summary>
    [GeneratedRegex(@"^[A-Za-z]{1,6}$", RegexOptions.CultureInvariant)]
    private static partial Regex UnitToken();

    [GeneratedRegex(@"^\d{1,9}(?:[.,]\d{1,3})?$", RegexOptions.CultureInvariant)]
    private static partial Regex Quantity();

    /// <summary>True when this text is an Aramco bid list. Cheap enough to call on everything.</summary>
    public static bool Recognises(string? text) =>
        !string.IsNullOrWhiteSpace(text)
        && text.Contains(Masthead, StringComparison.OrdinalIgnoreCase);

    /// <summary>
    /// Parses the document. Returns a <see cref="AramcoBidList.Rejection"/> instead of a partial
    /// result whenever the shape is not exactly what this template guarantees.
    /// </summary>
    public static AramcoBidList Parse(string? text)
    {
        if (!Recognises(text))
            return Empty("The document does not carry the Aramco e-bidding masthead.");

        var lines = text!
            .Replace("\r\n", "\n").Replace('\r', '\n')
            .Split('\n')
            .Select(l => l.Trim())
            .Where(l => l.Length > 0)
            .ToList();

        var headerEnd = FindColumnHeaderBlock(lines);
        if (headerEnd < 0)
            return Empty("The six-column header block was not found in the expected order.");

        var (bidno, vendor, buyer, bidDate, bidClose) = ReadHeader(lines, headerEnd);

        var parsed = new List<AramcoBidLine>();
        var index = headerEnd;

        while (index < lines.Count)
        {
            var start = NextRecordStart(lines, index);
            if (start < 0) break;

            // FIELDS ARE IDENTIFIED BY SHAPE, NOT BY POSITION.
            //
            // Ship To is optional — it is blank on real documents — so a fixed five-value
            // record reads the unit as a plant code and the quantity as a unit, and refuses a
            // perfectly good bid. Shapes are unambiguous here: the material number is nine
            // digits, a plant code is a short number, a unit is alphabetic, a quantity is
            // numeric. Anything that does not fit exactly one shape is refused rather than
            // assigned to the nearest column.
            if (start + 3 >= lines.Count)
                return Empty($"A record beginning at line {start} is truncated.");

            var bidLine = lines[start];
            var itemNo  = lines[start + 1];

            if (!MaterialNumber().IsMatch(itemNo))
                return Empty($"Line {start + 1} should be a material number but reads '{Clip(itemNo)}'.");

            string? shipTo;
            string unit;
            string qtyText;
            int fieldEnd;

            if (UnitToken().IsMatch(lines[start + 2]))
            {
                // Ship To omitted: item, unit, quantity.
                shipTo = null;
                unit = lines[start + 2];
                qtyText = start + 3 < lines.Count ? lines[start + 3] : string.Empty;
                fieldEnd = start + 4;
            }
            else if (start + 4 < lines.Count && UnitToken().IsMatch(lines[start + 3]))
            {
                // Ship To present: item, plant, unit, quantity.
                shipTo = lines[start + 2];
                unit = lines[start + 3];
                qtyText = lines[start + 4];
                fieldEnd = start + 5;
            }
            else
            {
                return Empty(
                    $"Item {itemNo} is followed by '{Clip(lines[start + 2])}', which is neither a "
                    + "unit of measure nor a plant code; the column order is not the expected one.");
            }

            if (!Quantity().IsMatch(qtyText)
                || !decimal.TryParse(qtyText.Replace(",", ""), NumberStyles.Number,
                        CultureInfo.InvariantCulture, out var qty))
                return Empty($"Item {itemNo} should carry a quantity but reads '{Clip(qtyText)}'.");
            if (qty <= 0)
                return Empty($"Item {itemNo} states a quantity of {qty}, which cannot be quoted.");

            // The description runs to the next record, or to the end of the document.
            var next = NextRecordStart(lines, fieldEnd);
            var stop = next < 0 ? lines.Count : next;
            var description = string.Join("\n", lines.Skip(fieldEnd).Take(stop - fieldEnd));

            if (description.Length == 0)
                return Empty($"Item {itemNo} carries no description.");

            parsed.Add(new AramcoBidLine(bidLine, itemNo, shipTo ?? string.Empty, unit, qty, description));
            index = stop;
        }

        if (parsed.Count == 0)
            return Empty("No line items were found beneath the column header.");

        // CROSS-CHECK. The material numbers are the one thing that cannot be miscounted, so a
        // parse that produced a different number of records than the document contains codes
        // has silently skipped or invented a line. Refuse rather than under-quote.
        var codes = lines.Count(MaterialNumber().IsMatch);
        if (codes != parsed.Count)
            return Empty(
                $"The document contains {codes} material number(s) but {parsed.Count} record(s) "
                + "were read; the layout is not the one this template expects.");

        return new AramcoBidList(parsed, bidno, vendor, buyer, bidDate, bidClose, null);
    }

    /// <summary>
    /// The header's six labels appear consecutively, and the first record follows them. A note
    /// paragraph sometimes sits between the two, so the search skips non-record prose rather
    /// than assuming a fixed offset.
    /// </summary>
    private static int FindColumnHeaderBlock(List<string> lines)
    {
        for (var i = 0; i + ColumnHeaders.Length <= lines.Count; i++)
        {
            var matched = true;
            for (var c = 0; c < ColumnHeaders.Length; c++)
            {
                if (!string.Equals(lines[i + c], ColumnHeaders[c], StringComparison.OrdinalIgnoreCase))
                {
                    matched = false;
                    break;
                }
            }
            if (matched) return i + ColumnHeaders.Length;
        }
        return -1;
    }

    /// <summary>
    /// A record opens with a bid-line number IMMEDIATELY followed by a material number. Either
    /// token alone is ambiguous — a plant code is a bare number too — so both are required.
    /// </summary>
    private static int NextRecordStart(List<string> lines, int from)
    {
        for (var i = Math.Max(0, from); i + 1 < lines.Count; i++)
            if (BidLineNumber().IsMatch(lines[i]) && MaterialNumber().IsMatch(lines[i + 1]))
                return i;
        return -1;
    }

    /// <summary>
    /// The masthead block writes its labels and then its values, so a value is read at the same
    /// offset past the label row. Every field is optional: a missing buyer name is not a reason
    /// to refuse a document whose line items are perfectly readable.
    /// </summary>
    private static (string? Bidno, string? Vendor, string? Buyer, DateOnly? Date, DateOnly? Close)
        ReadHeader(List<string> lines, int limit)
    {
        string? bidno = null, vendor = null, buyer = null;
        DateOnly? date = null, close = null;

        var labels = lines.Take(limit).ToList();
        var anchor = labels.FindIndex(l => l.Equals("Vendor Code", StringComparison.OrdinalIgnoreCase));
        if (anchor >= 0 && anchor + 9 < labels.Count)
        {
            // Vendor Code | Vendname | Bidno | Bid Date | Bid Close  →  five values follow.
            vendor = Value(labels, anchor + 5);
            bidno  = Value(labels, anchor + 7);
            date   = Date(Value(labels, anchor + 8));
            close  = Date(Value(labels, anchor + 9));
        }

        var buyerLabel = labels.FindIndex(l => l.Equals("Buyer", StringComparison.OrdinalIgnoreCase));
        if (buyerLabel >= 0 && buyerLabel + 2 < labels.Count) buyer = Value(labels, buyerLabel + 2);

        return (bidno, vendor, buyer, date, close);
    }

    private static string? Value(List<string> lines, int index) =>
        index >= 0 && index < lines.Count && lines[index].Length > 0 ? lines[index] : null;

    private static DateOnly? Date(string? value) =>
        DateOnly.TryParse(value, CultureInfo.InvariantCulture, DateTimeStyles.None, out var parsed)
            ? parsed : null;

    private static string Clip(string value) => value.Length <= 40 ? value : value[..40];

    private static AramcoBidList Empty(string rejection) =>
        new(Array.Empty<AramcoBidLine>(), null, null, null, null, null, rejection);
}
