import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Alert, Box, Button, Chip, CircularProgress, Paper, Stack, Tab, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, Tabs, Typography } from "@mui/material";
import { Refresh } from "@mui/icons-material";
import commercialLearningService, { type CurrencyValueSummary } from "../../api/services/commercialLearningService";

const value = (group?: CurrencyValueSummary) => group?.medianValue == null ? "No verified sample" :
  `${group.currencyCode} ${group.medianValue.toLocaleString(undefined, { maximumFractionDigits: 4 })} (${group.sampleSize})`;

export default function CommercialMemoryPage() {
  const [tab, setTab] = useState(0);
  const products = useQuery({ queryKey: ["commercial-learning", "products"], queryFn: () => commercialLearningService.getProducts() });
  const suppliers = useQuery({ queryKey: ["commercial-learning", "suppliers"], queryFn: () => commercialLearningService.getSuppliers() });
  const customers = useQuery({ queryKey: ["commercial-learning", "customers"], queryFn: () => commercialLearningService.getCustomers() });
  const salesReps = useQuery({ queryKey: ["commercial-learning", "sales-reps"], queryFn: () => commercialLearningService.getSalesReps() });
  const studio = useQuery({ queryKey: ["commercial-learning", "studio"], queryFn: commercialLearningService.getStudio });
  const loading = products.isLoading || suppliers.isLoading || customers.isLoading || salesReps.isLoading || studio.isLoading;
  const failed = products.isError || suppliers.isError || customers.isError || salesReps.isError || studio.isError;
  if (loading) return <Box sx={{ minHeight: "60vh", display: "grid", placeItems: "center" }}><CircularProgress /></Box>;
  return <Box sx={{ p: { xs: 2, md: 3 }, maxWidth: 1500, mx: "auto" }}>
    <Stack direction={{ xs: "column", md: "row" }} spacing={2} sx={{ justifyContent: "space-between", mb: 2 }}>
      <Box><Typography variant="h5" sx={{ fontWeight: 800 }}>Commercial Memory</Typography><Typography color="text.secondary">Verified outcomes, pricing evidence, demand, and approved corrections</Typography></Box>
      <Button startIcon={<Refresh />} onClick={() => { void products.refetch(); void suppliers.refetch(); void customers.refetch(); void salesReps.refetch(); void studio.refetch(); }}>Refresh</Button>
    </Stack>
    {failed && <Alert severity="error" sx={{ mb: 2 }}>Commercial evidence could not be loaded.</Alert>}
    <Paper variant="outlined" sx={{ mb: 2 }}><Tabs value={tab} onChange={(_, next) => setTab(next)} variant="scrollable"><Tab label="Product memory" /><Tab label="Supplier evaluation" /><Tab label="Sales Rep evaluation" /><Tab label="Customer outcomes" /><Tab label="Learning Studio" /></Tabs></Paper>
    {tab === 0 && <TableContainer component={Paper} variant="outlined"><Table size="small"><TableHead><TableRow><TableCell>Product</TableCell><TableCell align="right">Requested</TableCell><TableCell align="right">Quoted</TableCell><TableCell align="right">Decided</TableCell><TableCell align="right">Won / Lost / Pending</TableCell><TableCell align="right">Win rate</TableCell><TableCell>Last won context</TableCell><TableCell>Won selling price median</TableCell><TableCell>Supplier landed median</TableCell><TableCell>Evidence period</TableCell></TableRow></TableHead><TableBody>
      {(products.data ?? []).map((row) => <TableRow key={row.productId}><TableCell><Typography sx={{ fontWeight: 700 }}>{row.partNumber}</Typography><Typography variant="caption">{row.productName}</Typography></TableCell><TableCell align="right">{row.timesRequested}</TableCell><TableCell align="right">{row.timesQuoted}</TableCell><TableCell align="right">{row.decidedCount}</TableCell><TableCell align="right">{row.wonCount} / {row.lostCount} / {row.pendingCount}</TableCell><TableCell align="right">{row.lineWinRatePercent == null ? "Insufficient evidence" : `${row.lineWinRatePercent}%`}</TableCell><TableCell>{row.lastWonContext == null ? "No verified win" : <>{row.lastWonContext.customerQuoteNumber}: {row.lastWonContext.quantity} at {row.lastWonContext.currencyCode} {row.lastWonContext.unitPrice}<Typography variant="caption" sx={{ display: "block" }}>{row.lastWonContext.deliveryLeadTimeDays == null ? "Lead time not recorded" : `${row.lastWonContext.deliveryLeadTimeDays} days`}</Typography></>}</TableCell><TableCell>{value(row.wonSellingPrices[0])}</TableCell><TableCell>{value(row.supplierLandedCosts[0])}</TableCell><TableCell>{new Date(row.periodFrom).toLocaleDateString()} to {new Date(row.periodTo).toLocaleDateString()}<Typography variant="caption" sx={{ display: "block" }}>{row.stockoutBlockedCount} stockout-blocked</Typography></TableCell></TableRow>)}
      {(products.data?.length ?? 0) === 0 && <TableRow><TableCell colSpan={10} align="center">No Product outcome evidence is available yet.</TableCell></TableRow>}
    </TableBody></Table></TableContainer>}
    {tab === 1 && <TableContainer component={Paper} variant="outlined"><Table size="small"><TableHead><TableRow><TableCell>Supplier</TableCell><TableCell align="right">Quote revisions</TableCell><TableCell align="right">Current complete offers</TableCell><TableCell align="right">Selected</TableCell><TableCell align="right">Supported wins</TableCell><TableCell align="right">Average response</TableCell><TableCell>Landed-cost median</TableCell><TableCell>Evidence</TableCell></TableRow></TableHead><TableBody>
      {(suppliers.data ?? []).map((row) => <TableRow key={row.supplierId}><TableCell sx={{ fontWeight: 700 }}>{row.supplierName}</TableCell><TableCell align="right">{row.quoteRevisions}</TableCell><TableCell align="right">{row.completeCurrentOfferCount}</TableCell><TableCell align="right">{row.selectedOfferCount}</TableCell><TableCell align="right">{row.supportedWonCount}</TableCell><TableCell align="right">{row.averageResponseDays == null ? "No verified sample" : `${row.averageResponseDays} days`}</TableCell><TableCell>{value(row.landedCosts[0])}</TableCell><TableCell>{row.evidence.length} linked records</TableCell></TableRow>)}
      {(suppliers.data?.length ?? 0) === 0 && <TableRow><TableCell colSpan={8} align="center">No verified Supplier Quote evidence is available yet.</TableCell></TableRow>}
    </TableBody></Table></TableContainer>}
    {tab === 2 && <TableContainer component={Paper} variant="outlined"><Table size="small"><TableHead><TableRow><TableCell>Sales Rep</TableCell><TableCell align="right">Owned opportunities</TableCell><TableCell align="right">Won / Lost</TableCell><TableCell align="right">Conversion</TableCell><TableCell align="right">Commercial constraints</TableCell><TableCell align="right">Customer decisions</TableCell><TableCell align="right">Execution review</TableCell><TableCell align="right">Follow-ups due / completed</TableCell></TableRow></TableHead><TableBody>
      {(salesReps.data ?? []).map((row) => <TableRow key={row.salesRepUserId}><TableCell sx={{ fontWeight: 700 }}>{row.salesRepName}</TableCell><TableCell align="right">{row.ownedOpportunities}</TableCell><TableCell align="right">{row.wonCount} / {row.lostCount}</TableCell><TableCell align="right">{row.conversionRatePercent == null ? "Insufficient evidence" : `${row.conversionRatePercent}%`}</TableCell><TableCell align="right">{row.commercialConstraintLosses}</TableCell><TableCell align="right">{row.customerDecisionLosses}</TableCell><TableCell align="right">{row.executionReviewLosses}</TableCell><TableCell align="right">{row.followUpsDue} / {row.followUpsCompleted}</TableCell></TableRow>)}
      {(salesReps.data?.length ?? 0) === 0 && <TableRow><TableCell colSpan={8} align="center">No assigned opportunity outcomes are available yet.</TableCell></TableRow>}
    </TableBody></Table></TableContainer>}
    {tab === 3 && <TableContainer component={Paper} variant="outlined"><Table size="small"><TableHead><TableRow><TableCell>Customer</TableCell><TableCell align="right">Inquiries</TableCell><TableCell align="right">Quotes</TableCell><TableCell align="right">Won / Lost / Pending</TableCell><TableCell align="right">Conversion</TableCell><TableCell>Won value median</TableCell><TableCell>Recorded loss factors</TableCell><TableCell>Evidence</TableCell></TableRow></TableHead><TableBody>
      {(customers.data ?? []).map((row) => <TableRow key={row.customerId}><TableCell sx={{ fontWeight: 700 }}>{row.customerName}</TableCell><TableCell align="right">{row.inquiryCount}</TableCell><TableCell align="right">{row.quoteCount}</TableCell><TableCell align="right">{row.wonCount} / {row.lostCount} / {row.pendingCount}</TableCell><TableCell align="right">{row.conversionRatePercent == null ? "Insufficient evidence" : `${row.conversionRatePercent}%`}</TableCell><TableCell>{value(row.wonValues[0])}</TableCell><TableCell>{row.lossReasons.length === 0 ? "None recorded" : row.lossReasons.map((reason) => `${reason.label}: ${reason.count}`).join(", ")}</TableCell><TableCell>{row.evidence.length} linked records</TableCell></TableRow>)}
      {(customers.data?.length ?? 0) === 0 && <TableRow><TableCell colSpan={8} align="center">No Customer Quote outcomes are available yet.</TableCell></TableRow>}
    </TableBody></Table></TableContainer>}
    {tab === 4 && studio.data && <Stack spacing={2}>
      <Box sx={{ display: "grid", gridTemplateColumns: { xs: "1fr 1fr", md: "repeat(5, 1fr)" }, gap: 2 }}>
        {[["Approved corrections", studio.data.approvedCorrections], ["Conflicts", studio.data.conflictingCorrections], ["Source templates", studio.data.supplierQuoteTemplates], ["Decision-ready products", studio.data.productMemoriesWithDecisions], ["Below threshold", studio.data.productMemoriesBelowThreshold]].map(([label, count]) => <Box key={String(label)}><Typography variant="caption" color="text.secondary">{label}</Typography><Typography variant="h5" sx={{ fontWeight: 800 }}>{count}</Typography></Box>)}
      </Box>
      {studio.data.conflictingCorrections > 0 && <Alert severity="warning">Conflicting approved corrections require human review before reuse.</Alert>}
      <TableContainer component={Paper} variant="outlined"><Table size="small"><TableHead><TableRow><TableCell>Learned signal</TableCell><TableCell>Approved value</TableCell><TableCell align="right">Samples</TableCell><TableCell>Status</TableCell><TableCell>Last observed</TableCell><TableCell>Evidence</TableCell></TableRow></TableHead><TableBody>{studio.data.recentSignals.map((signal) => <TableRow key={`${signal.evidenceReference}:${signal.subject}`}><TableCell>{signal.subject}</TableCell><TableCell>{signal.value}</TableCell><TableCell align="right">{signal.sampleSize}</TableCell><TableCell><Chip size="small" color={signal.status === "CONFLICT_REVIEW" ? "warning" : signal.status === "REUSABLE" ? "success" : "default"} label={signal.status.replaceAll("_", " ")} /></TableCell><TableCell>{new Date(signal.lastObservedOn).toLocaleString()}</TableCell><TableCell>{signal.evidenceReference}</TableCell></TableRow>)}{studio.data.recentSignals.length === 0 && <TableRow><TableCell colSpan={6} align="center">No approved correction signals are available yet.</TableCell></TableRow>}</TableBody></Table></TableContainer>
    </Stack>}
  </Box>;
}
